name: embedded-misc-utils # you probably want to 'snapcraft register <name>'
version: '0.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple collection of tools to test embedded systems # 79 char long summary
description: |
  This is a collection of hardware/software test utilities for embedded systems
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
        fbtest:
                command: fbtest

parts:
  embedded-misc-utils:
    # See 'snapcraft plugins'
    source: git://github.com/taiten/embedded-misc-utils
    plugin: make


