name: embedded-misc-utils # you probably want to 'snapcraft register <name>'
version: '0.9' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple collection of tools to test embedded systems # 79 char long summary
description: |
  This is a collection of hardware/software test utilities for embedded systems
base: core
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  fbtest:
    command: bin/fbtest
  hello:
    command: bin/hello

parts:
  embedded-misc-utils:
    # See 'snapcraft plugins'
    source: src
    plugin: make
